// This file is auto-generated by @hey-api/openapi-ts

export const HelloResponseSchema = {
    type: 'object',
    description: '',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string',
            description: '',
            example: 'https://шаховпобеда.рф'
        }
    }
} as const;

export const JsonCompleteMarketplaceAnalysisSchema = {
    type: 'object',
    description: '',
    required: [
        'predicted_price',
        'stats',
        'analyses'
    ],
    properties: {
        predicted_price: {
            type: 'number',
            format: 'double',
            description: '',
            example: 3800000,
            minimum: 0
        },
        stats: {
            $ref: '#/components/schemas/JsonStats'
        },
        analyses: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/JsonMarketplaceAnalysis'
            },
            description: ''
        }
    }
} as const;

export const JsonMarketplaceSchema = {
    type: 'string',
    description: '',
    enum: [
        'Wildberries',
        'Ozon'
    ]
} as const;

export const JsonMarketplaceAnalysisSchema = {
    type: 'object',
    description: '',
    required: [
        'marketplace',
        'can_open',
        'tariffs'
    ],
    properties: {
        marketplace: {
            $ref: '#/components/schemas/JsonMarketplace'
        },
        can_open: {
            type: 'boolean',
            description: ''
        },
        tariffs: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/JsonTariff'
            },
            description: '',
            minItems: 0
        },
        subsidy: {
            nullable: true,
            allOf: [
                {
                    $ref: '#/components/schemas/JsonSubsidy'
                }
            ]
        }
    }
} as const;

export const JsonStatsSchema = {
    type: 'object',
    description: '',
    required: [
        'population',
        'count_wb',
        'count_ozon',
        'count_pharmacies',
        'count_metro',
        'count_shops',
        'count_commercials',
        'count_platforms'
    ],
    properties: {
        population: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 3800000,
            minimum: 0
        },
        count_wb: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_ozon: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_pharmacies: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_metro: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_shops: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_commercials: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        },
        count_platforms: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 7,
            minimum: 0
        }
    }
} as const;

export const JsonSubsidySchema = {
    type: 'object',
    description: '',
    required: [
        'subsidy_type',
        'subsidy_size'
    ],
    properties: {
        subsidy_type: {
            $ref: '#/components/schemas/JsonSubsidyType'
        },
        subsidy_size: {
            type: 'integer',
            format: 'int32',
            description: '',
            example: 3800000,
            minimum: 0
        }
    }
} as const;

export const JsonSubsidyTypeSchema = {
    type: 'string',
    description: '',
    enum: [
        'NORMAL',
        'GUARANTEED',
        'NONE'
    ]
} as const;

export const JsonTariffSchema = {
    type: 'object',
    description: '',
    required: [
        'total_tariff'
    ],
    properties: {
        total_tariff: {
            type: 'number',
            format: 'float',
            description: '',
            example: 7,
            maximum: 100,
            minimum: 0
        }
    }
} as const;
