// This file is auto-generated by @hey-api/openapi-ts

export const CountryNameDtoSchema = {
    type: 'object',
    properties: {
        common: {
            type: 'string',
            example: 'Aruba',
            description: 'Common name of the country'
        },
        official: {
            type: 'string',
            example: 'Aruba',
            description: 'Official name of the country'
        },
        native: {
            type: 'object',
            example: {
                nld: {
                    official: 'Aruba',
                    common: 'Aruba'
                },
                pap: {
                    official: 'Aruba',
                    common: 'Aruba'
                }
            },
            description: 'Native names in different languages',
            additionalProperties: {
                type: 'object',
                properties: {
                    official: {
                        type: 'string'
                    },
                    common: {
                        type: 'string'
                    }
                }
            }
        }
    },
    required: [
        'common',
        'official',
        'native'
    ]
} as const;

export const IddDtoSchema = {
    type: 'object',
    properties: {
        root: {
            type: 'string',
            example: '+2',
            description: 'International dialing root code'
        },
        suffixes: {
            example: [
                '97'
            ],
            description: 'International dialing suffixes',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'root',
        'suffixes'
    ]
} as const;

export const CountryResponseDtoSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'Country name information',
            example: {
                common: 'Aruba',
                official: 'Aruba',
                native: {
                    nld: {
                        official: 'Aruba',
                        common: 'Aruba'
                    },
                    pap: {
                        official: 'Aruba',
                        common: 'Aruba'
                    }
                }
            },
            allOf: [
                {
                    $ref: '#/components/schemas/CountryNameDto'
                }
            ]
        },
        tld: {
            example: [
                '.aw'
            ],
            description: 'Top-level domain',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        cca2: {
            type: 'string',
            example: 'AW',
            description: 'ISO 3166-1 alpha-2 code'
        },
        ccn3: {
            type: 'string',
            example: '533',
            description: 'ISO 3166-1 numeric code'
        },
        cca3: {
            type: 'string',
            example: 'ABW',
            description: 'ISO 3166-1 alpha-3 code'
        },
        cioc: {
            type: 'string',
            example: 'ARU',
            description: 'International Olympic Committee code'
        },
        independent: {
            type: 'boolean',
            example: false,
            description: 'Whether the country is independent'
        },
        status: {
            type: 'string',
            example: 'officially-assigned',
            description: 'Status of the country'
        },
        unMember: {
            type: 'boolean',
            example: false,
            description: 'Whether the country is a UN member'
        },
        unRegionalGroup: {
            type: 'string',
            example: '',
            description: 'UN regional group'
        },
        currencies: {
            type: 'object',
            example: {
                AWG: {
                    name: 'Aruban florin',
                    symbol: 'ƒ'
                }
            },
            description: 'Currencies used in the country',
            additionalProperties: {
                type: 'object',
                properties: {
                    name: {
                        type: 'string'
                    },
                    symbol: {
                        type: 'string'
                    }
                }
            }
        },
        idd: {
            description: 'International dialing code information',
            example: {
                root: '+2',
                suffixes: [
                    '97'
                ]
            },
            allOf: [
                {
                    $ref: '#/components/schemas/IddDto'
                }
            ]
        },
        capital: {
            example: [
                'Oranjestad'
            ],
            description: 'Capital cities',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        altSpellings: {
            example: [
                'AW'
            ],
            description: 'Alternative spellings',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        region: {
            type: 'string',
            example: 'Americas',
            description: 'Geographic region'
        },
        subregion: {
            type: 'string',
            example: 'Caribbean',
            description: 'Geographic subregion'
        },
        languages: {
            type: 'object',
            example: {
                nld: 'Dutch',
                pap: 'Papiamento'
            },
            description: 'Languages spoken in the country',
            additionalProperties: {
                type: 'string'
            }
        },
        translations: {
            type: 'object',
            example: {
                ara: {
                    official: 'أروبا',
                    common: 'أروبا'
                },
                eng: {
                    official: 'Aruba',
                    common: 'Aruba'
                },
                rus: {
                    official: 'Аруба',
                    common: 'Аруба'
                }
            },
            description: 'Translations of country name in different languages',
            additionalProperties: {
                type: 'object',
                properties: {
                    official: {
                        type: 'string'
                    },
                    common: {
                        type: 'string'
                    }
                }
            }
        },
        latlng: {
            example: [
                12.5,
                -69.96666666
            ],
            description: 'Latitude and longitude coordinates',
            type: 'array',
            items: {
                type: 'number'
            }
        },
        landlocked: {
            type: 'boolean',
            example: false,
            description: 'Whether the country is landlocked'
        },
        borders: {
            example: [],
            description: 'Border country codes (ISO 3166-1 alpha-3)',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        area: {
            type: 'number',
            example: 180,
            description: 'Area in square kilometers'
        },
        flag: {
            type: 'string',
            example: '🇦🇼',
            description: 'Country flag emoji'
        },
        demonyms: {
            type: 'object',
            example: {
                eng: {
                    f: 'Aruban',
                    m: 'Aruban'
                },
                fra: {
                    f: 'Arubaise',
                    m: 'Arubais'
                }
            },
            description: 'Demonyms (what people from this country are called)',
            additionalProperties: {
                type: 'object',
                properties: {
                    f: {
                        type: 'string',
                        description: 'Female form'
                    },
                    m: {
                        type: 'string',
                        description: 'Male form'
                    }
                }
            }
        },
        population: {
            type: 'number',
            example: 105845,
            description: 'Population'
        }
    },
    required: [
        'name',
        'tld',
        'cca2',
        'ccn3',
        'cca3',
        'cioc',
        'status',
        'unMember',
        'unRegionalGroup',
        'currencies',
        'idd',
        'capital',
        'altSpellings',
        'region',
        'subregion',
        'languages',
        'translations',
        'latlng',
        'landlocked',
        'borders',
        'area',
        'flag',
        'demonyms',
        'population'
    ]
} as const;
