// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CountriesControllerGetCountriesData, CountriesControllerGetCountriesResponses, CountriesControllerGetCountryData, CountriesControllerGetCountryResponses, CountriesControllerGetHealthData, CountriesControllerGetHealthResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const countriesControllerGetHealth = <ThrowOnError extends boolean = false>(options?: Options<CountriesControllerGetHealthData, ThrowOnError>) => (options?.client ?? client).get<CountriesControllerGetHealthResponses, unknown, ThrowOnError>({ url: '/server/countries/health', ...options });

/**
 * Get information about countries
 */
export const countriesControllerGetCountries = <ThrowOnError extends boolean = false>(options?: Options<CountriesControllerGetCountriesData, ThrowOnError>) => (options?.client ?? client).get<CountriesControllerGetCountriesResponses, unknown, ThrowOnError>({ url: '/server/countries', ...options });

/**
 * Get information about a specific country
 */
export const countriesControllerGetCountry = <ThrowOnError extends boolean = false>(options: Options<CountriesControllerGetCountryData, ThrowOnError>) => (options.client ?? client).get<CountriesControllerGetCountryResponses, unknown, ThrowOnError>({ url: '/server/countries/{countryId}', ...options });
