// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CountryNameDto = {
    /**
     * Common name of the country
     */
    common: string;
    /**
     * Official name of the country
     */
    official: string;
    /**
     * Native names in different languages
     */
    native: {
        [key: string]: {
            official?: string;
            common?: string;
        };
    };
};

export type IddDto = {
    /**
     * International dialing root code
     */
    root: string;
    /**
     * International dialing suffixes
     */
    suffixes: Array<string>;
};

export type CountryResponseDto = {
    /**
     * Country name information
     */
    name: CountryNameDto;
    /**
     * Top-level domain
     */
    tld: Array<string>;
    /**
     * ISO 3166-1 alpha-2 code
     */
    cca2: string;
    /**
     * ISO 3166-1 numeric code
     */
    ccn3: string;
    /**
     * ISO 3166-1 alpha-3 code
     */
    cca3: string;
    /**
     * International Olympic Committee code
     */
    cioc: string;
    /**
     * Whether the country is independent
     */
    independent?: boolean;
    /**
     * Status of the country
     */
    status: string;
    /**
     * Whether the country is a UN member
     */
    unMember: boolean;
    /**
     * UN regional group
     */
    unRegionalGroup: string;
    /**
     * Currencies used in the country
     */
    currencies: {
        [key: string]: {
            name?: string;
            symbol?: string;
        };
    };
    /**
     * International dialing code information
     */
    idd: IddDto;
    /**
     * Capital cities
     */
    capital: Array<string>;
    /**
     * Alternative spellings
     */
    altSpellings: Array<string>;
    /**
     * Geographic region
     */
    region: string;
    /**
     * Geographic subregion
     */
    subregion: string;
    /**
     * Languages spoken in the country
     */
    languages: {
        [key: string]: string;
    };
    /**
     * Translations of country name in different languages
     */
    translations: {
        [key: string]: {
            official?: string;
            common?: string;
        };
    };
    /**
     * Latitude and longitude coordinates
     */
    latlng: Array<number>;
    /**
     * Whether the country is landlocked
     */
    landlocked: boolean;
    /**
     * Border country codes (ISO 3166-1 alpha-3)
     */
    borders: Array<string>;
    /**
     * Area in square kilometers
     */
    area: number;
    /**
     * Country flag emoji
     */
    flag: string;
    /**
     * Demonyms (what people from this country are called)
     */
    demonyms: {
        [key: string]: {
            /**
             * Female form
             */
            f?: string;
            /**
             * Male form
             */
            m?: string;
        };
    };
    /**
     * Population
     */
    population: number;
};

export type CountriesControllerGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/countries/health';
};

export type CountriesControllerGetHealthResponses = {
    200: unknown;
};

export type CountriesControllerGetCountriesData = {
    body?: never;
    path?: never;
    query?: {
        start?: number;
        end?: number;
        search?: string;
        sortBy?: string;
    };
    url: '/countries';
};

export type CountriesControllerGetCountriesResponses = {
    /**
     * Countries information
     */
    200: Array<CountryResponseDto>;
};

export type CountriesControllerGetCountriesResponse = CountriesControllerGetCountriesResponses[keyof CountriesControllerGetCountriesResponses];

export type CountriesControllerGetCountryData = {
    body?: never;
    path: {
        countryId: string;
    };
    query?: never;
    url: '/countries/{countryId}';
};

export type CountriesControllerGetCountryResponses = {
    /**
     * Country information (returns null if country not found)
     */
    200: CountryResponseDto;
};

export type CountriesControllerGetCountryResponse = CountriesControllerGetCountryResponses[keyof CountriesControllerGetCountryResponses];
