// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type CountriesControllerGetCountriesData = {
    body?: never;
    path?: never;
    query: {
        start: number;
        end: number;
    };
    url: '/countries';
};

export type CountriesControllerGetCountriesResponses = {
    /**
     * Countries information
     */
    200: unknown;
};

export type CountriesControllerGetCountryData = {
    body?: never;
    path: {
        countryId: string;
    };
    query?: never;
    url: '/countries/{countryId}';
};

export type CountriesControllerGetCountryResponses = {
    /**
     * Country information
     */
    200: unknown;
};
