// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/v0' | (string & {});
};

export type HelloResponse = {
    message: string;
};

export type JsonCompleteMarketplaceAnalysis = {
    predicted_price: number;
    stats: JsonStats;
    analyses: Array<JsonMarketplaceAnalysis>;
};

export const JsonMarketplace = { WILDBERRIES: 'Wildberries', OZON: 'Ozon' } as const;

export type JsonMarketplace = typeof JsonMarketplace[keyof typeof JsonMarketplace];

export type JsonMarketplaceAnalysis = {
    marketplace: JsonMarketplace;
    can_open: boolean;
    tariffs: Array<JsonTariff>;
    subsidy?: JsonSubsidy | null;
};

export type JsonStats = {
    population: number;
    count_wb: number;
    count_ozon: number;
    count_pharmacies: number;
    count_metro: number;
    count_shops: number;
    count_commercials: number;
    count_platforms: number;
};

export type JsonSubsidy = {
    subsidy_type: JsonSubsidyType;
    subsidy_size: number;
};

export const JsonSubsidyType = {
    NORMAL: 'NORMAL',
    GUARANTEED: 'GUARANTEED',
    NONE: 'NONE'
} as const;

export type JsonSubsidyType = typeof JsonSubsidyType[keyof typeof JsonSubsidyType];

export type JsonTariff = {
    total_tariff: number;
};

export type HelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type HelloResponses = {
    /**
     * Java gnomes?
     */
    200: HelloResponse;
};

export type HelloResponse2 = HelloResponses[keyof HelloResponses];

export type AnalyzeData = {
    body?: never;
    path?: never;
    query: {
        latitude: number;
        longitude: number;
        address: string;
        area: number;
    };
    url: '/analyze';
};

export type AnalyzeResponses = {
    200: JsonCompleteMarketplaceAnalysis;
};

export type AnalyzeResponse = AnalyzeResponses[keyof AnalyzeResponses];
