import '@/styles/globals.css';

import { ThemeProvider } from '@shadcn/theme-provider';
import { Metadata } from 'next';

import Footer from '@/components/footer/footer';
import Header from '@/components/header/header';
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: '/favicon.ico',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ru en" suppressHydrationWarning className="overflow-y-scroll">
			<body className="antialiased flex flex-col min-h-screen">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<main className="flex-1">{children}</main>
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
